spring:
   datasource:
     initialization-mode: always
     url: jdbc:postgresql://localhost:5432/bank
     username: postgres
     password: postgres
   jpa:
     properties:
       hibernate:
         jdbc:
           lob:
             non_contextual_creation: true
     show-sql: true
     hibernate:
       use-new-id-generator-mappings: false